### ISSUE TITLE
EAC - manual ban by dev team

### ISSUE THREAD

**Issue by maxensas** [maxensas/lastgarriz#1]
If you encounter this message when you try to play the game, please fill this thread with your use case.
It is quite possible that the development team decided to add this tool to an internal blacklist without any discuss.

This project has no bad intentions and will be updated accordingly if Team17 believes that the tool brings a real advantage in the game compared to the average player.

**Comment by Aimless321** [comment]
I tried it out for 10 minutes yesterday, and got permanently banned.
You should probably put up a big warning message in the readme.

![image](https://user-images.githubusercontent.com/6079485/226836654-2f3e9675-9520-466c-bb97-c511665d900a.png)

**Comment by Aimless321** [comment]
I just got it confirmed by the the support team of T17, that they decided to ban this tool.

![Screenshot 2023-03-22 110248](https://user-images.githubusercontent.com/6079485/226878107-0c2b1699-2db5-4d6c-b231-0fa9a50bb013.png)

**Comment by Harry25125** [comment]
I got banned today because of this

**Comment by MonkeyyNinja** [comment]
I hadn't even played since the 19th and I just got a ban message today. Someone at T17 has made it their personal mission to shut this down.

**Comment by maxensas** [comment]
Here is the dated email sent to Team17 which allowed to reconsider some bans but not all unfortunately :

![mail](https://user-images.githubusercontent.com/62154281/228843277-7361401a-4e88-4851-af9b-5f66465ca42c.png)

This tool is not a cheat and has not been promoted by its author outside of this repository since its first version.
All binaries offered for download must be deleted as they are detected by the EAC blocklist when playing Hell Let Loose.

For people unfortunately impacted, you can submit an unban request on developer website as follow. 
https://support.team17.com/hc/en-gb/requests/new

**Comment by cabbagelol** [comment]
After communication, the accounts that finally use this tool are permanently banned, and the HELL team maintains the original judgment; Although the tool did not hack the program.

**Comment by maxensas** [comment]
For all people who are still banned by using Lastgarriz before April 2023 :

You can send an unban request on the official discord https://discord.com/invite/hellletloose by contacting the community manager 'WombatMedic'. Describe your problem politely in English and she will be able to act in your favor in order to recover your hll account even if you have already received a refusal by email.

And for your information,

Team 17 became interested in this project from March 14, 2023 and acted against it without communicating.

Any further use of binaries released on this repository after April 2023 will likely not be able to be unbanned, remains to be seen with new game developers currently in bad shape. These blacklisted executables were immediately removed on March 22, 2023 after receiving user feedback which led to an explicit warning message being posted on first page.

It should be remembered that Lastgarriz is an overlay and not a cheat. EAC offers a free service to block an application or device deemed unwanted by the author of the game. The Lastgarriz tool cannot be detected in the current state if you compile it yourself and will probably never be by seeing its low impact and the resources needed to deploy an effective countermeasure.

**Comment by LED-13** [comment]
> For all people who are still banned by using Lastgarriz before April 2023 :
> 
> You can send an unban request on the official discord https://discord.com/invite/hellletloose by contacting the community manager 'WombatMedic'. Describe your problem politely in English and she will be able to act in your favor in order to recover your hll account even if you have already received a refusal by email.
> 
> And for your information,
> 
> Team 17 became interested in this project from March 14, 2023 and acted against it without communicating.
> 
> Any further use of binaries released on this repository after April 2023 will likely not be able to be unbanned, remains to be seen with new game developers currently in bad shape. These blacklisted executables were immediately removed on March 22, 2023 after receiving user feedback which led to an explicit warning message being posted on first page.
> 
> It should be remembered that Lastgarriz is an overlay and not a cheat. EAC offers a free service to block an application or device deemed unwanted by the author of the game. The Lastgarriz tool cannot be detected in the current state if you compile it yourself and will probably never be by seeing its low impact and the resources needed to deploy an effective countermeasure.

Sorry for the reply on this closed issue, but Github does not allow pm...

I am interested in the way you make the crosshair it seems to be able to dynamically adjust itself to fit all resolutions. I had litte experince with C# winform apps but not WPF. I can't really find the part where the crosshair part works in your code. Do you mind explain a little?

Regarding to the part that you metioned about recompile the code ourself to bypass EAC. Doesn't recompile only affect the executable file? Wouldn't the dlls and other files get mark for their hash verification and path? It is not worth it to risk getting baned for this with this incomprehensible atitude from Team 17, who they should put more effort on those disruptive programs.

**Comment by maxensas** [comment]
No worries, I give you a quick answer.

- Adaptive crosshair
Hake a look on the viewmodel's associated (line 140) - It should be placed in a different Crosshair.cs file, my bad :
https://github.com/maxensas/lastgarriz/blob/main/Lastgarriz/ViewModels/RocketViewModel.cs
All measures (abscissa) has been taken in 1080p and are converted to your screen resolution by using 'AdjustAbscissaValue' method. 
The value obtained may therefore lack precision, not to mention the fact that the values were taken at the same altitude (departure and arrival of the rocket) and will never be fully accurate. 
It would have been better to take the values using 4K if I had the hardware.
Other note: Panzerschreck values are made before the U13, so its actually deprecated and we now have the PIAT aswell.

- About EAC
Team 17 added all hashes manually related to binaries realesed in this project, 4 in total since the beginning in their EAC account associated to Hell Let Loose. If you do not publish to a public repository, T17 can not have the bin hashes and EAC can not ban you for an unwanted software or device. I would have preferred to remain discreet on this subject since I do not tolerate the use of cheats as a competitive player.

- About DLLs
The project use references such as 'TesseractOCR' and 'Utf8Json' , they are embedded in lastgarriz binary.
The application is self contained, that mean you do not need to install a runtime or SDK. DLLs come from .NET 7 in order to work. It make sense that T17 cannot add thoses hashes or they are going to shoot themselves in the foot.

- T17 effort
To be honest with a good communication, i would have deleted this repository but that does not prevent other new projects to see the light. We are fully agree about human ressource allocation but they remain the game owners and they have the right to do what they want.
