### ISSUE TITLE
Appeal channel

### ISSUE THREAD

**Issue by cabbagelol** [maxensas/lastgarriz#2]
Sorry to open a new question to talk about EAC blocking. #1 

I am also a player who used lastgarriz in March and was banned

A few days ago, I saw an update to README.md where the developer said that some players had unblocked it.

I then contacted team17, but received a response that did not change the ban.

Please help me.

@maxensas

**Comment by maxensas** [comment]
Hi [cabbagelol](https://github.com/cabbagelol)
I do not have all the information concerning your ban, I am not T17 and as mentioned in the previous thread. 
You had to contact WombatMedic, the community manager on their Discord channel, describing your case clearly in English to hope to get a positive response in return. 
She was able to have several bans overturned unlike her colleagues several months ago when the subject was hot. 
Now i have no idea how they treat this subject.

**Comment by cabbagelol** [comment]
Thank you for your reply.
